# Generated by Django 3.1.7 on 2021-06-07 13:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210401_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_image',
            field=models.ImageField(blank=True, null=True, upload_to='./'),
        ),
    ]
