# Generated by Django 3.1.7 on 2021-06-07 18:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210607_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='uid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
